### ISSUE TITLE
Pattern matching error ao consultar a versão

### ISSUE THREAD

**Issue by GoedertDalmolin** [rodrigorahman/json_rest_server#26]
Estou obtendo `Bad state: Pattern matching error` após executar `json_rest_server version`.

Flutter Version: 3.19.5 (stable)
Dart SDK Version: 3.3.3 (stable)

 ### Steps to reproduce

1. Executar o comando:

`dart pub global activate json_rest_server`

<details><summary>output</summary>
<p>

```
Package json_rest_server is currently active at version 3.1.0.
The package json_rest_server is already activated at newest available version.
To recompile executables, first run dart pub global deactivate json_rest_server
Installed executables jrs, jsonRestServer and json_rest_server.
Activated json_rest_server 3.1.0.
```

</p>
</details> 

2. Executar o comando:

 `json_rest_server version`
 
 Onde obtive a seguinte saida:
 
```
Unhandled exception:
Bad state: Pattern matching error
#0      VersionCommand._parsePackagesVersion (package:json_rest_server/src/commands/version_command.dart:39:9)
#1      VersionCommand.run (package:json_rest_server/src/commands/version_command.dart:17:50)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#4      new Future.sync (dart:async/future.dart:305:31)
#5      CommandRunner.run (package:args/command_runner.dart:122:14)
#6      main (file:///C:/Users/gbrun/AppData/Local/Pub/Cache/hosted/pub.dev/json_rest_server-3.1.0/bin/json_rest_server.dart:14:7)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Unhandled exception:
Bad state: Pattern matching error
#0      VersionCommand._parsePackagesVersion (package:json_rest_server/src/commands/version_command.dart:39:9)
#1      VersionCommand.run (package:json_rest_server/src/commands/version_command.dart:17:50)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#4      new Future.sync (dart:async/future.dart:305:31)
#5      CommandRunner.run (package:args/command_runner.dart:122:14)
#6      main (file:///C:/Users/gbrun/AppData/Local/Pub/Cache/hosted/pub.dev/json_rest_server-3.1.0/bin/json_rest_server.dart:14:7)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### Doctor output
<details><summary>Doctor output</summary>
<p>

```
flutter doctor -v
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [versÆo 10.0.22631.3296], locale pt-BR)
    • Flutter version 3.19.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (10 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\gbrun\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Ferramentas de Build do Visual Studio 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Ferramentas de Build do Visual Studio 2019 version 16.11.34114.132
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.1)
    • VS Code at C:\Users\gbrun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22631.3296]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.106
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</p>
</details>

**Comment by rodrigorahman** [comment]
Resolvido na versão [3.20](https://pub.dev/packages/json_rest_server/versions/3.2.0)
